import "./globals.css";
import { Inter } from "next/font/google";
import { Providers } from "./provider";
import { ModalProvider } from "@/context/modalContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <title>페이지 이름</title>
      </head>
      <body className="Upper">
        <ModalProvider>
          <Providers>{children}</Providers>
        </ModalProvider>
      </body>
    </html>
  );
}
